### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by ankitdaf** [sengupta/twss#1]
You might want to include a small note that instructs how to get the system up and running for first-timers.

**Comment by sengupta** [comment]
I'll defer this for a bit because we are making a lot of changes that will affect how to get this up and running. Once we are a bit stable, I'll put this in. I'll leave the issue open.

**Comment by hiway** [comment]
For starters, run these commands inside the project directory:

virtualenv --no-site-packages --distribute venv
source venv/bin/activate
pip install -r requirements.txt

This will create and activate a virtual environment for your project, and finally install all the required libraries automatically.

Remember to run 'source venv/bin/activate' from your project directory every time you want to start working on the project.

For now try running 'python twss_server.py' and point browser to 'localhost:8080', should give you something to play with ;)

**Comment by sengupta** [comment]
Instructions are added.
